### ISSUE TITLE
Performance Umbrella ☂

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#426]
This issue can collect other issues related to performance in Ketrew:

### Issues
- [ ] [Very slow to build in big server](https://github.com/hammerlab/ketrew/issues/425)
- [ ] [Websockets instead of XHR to overcome connection limit](https://github.com/hammerlab/ketrew/issues/400)
- [ ] [Improve database model](https://github.com/hammerlab/ketrew/issues/423)
- [ ] [Optimize engine](https://github.com/hammerlab/ketrew/issues/73)

**Comment by ihodes** [comment]
Closing in favor of the new  performance label https://github.com/hammerlab/ketrew/issues?q=is%3Aopen+is%3Aissue+label%3Aperformance
